name: quran_kareem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  scrollable_positioned_list: ^0.2.3
  cupertino_icons: ^1.0.2
  share_plus: ^4.0.3
  url_launcher: ^6.1.6
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    #  شاشة البداية
  flutter_native_splash: ^2.2.16
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/quran.png
  # android_gravity: center
  # في حاله الوضع المظلم 
  color_dark: "#121B22"
  android: true
  ios: true
  # بعد كده اعمل رن للاوامر دي
  # flutter clean 
  # flutter pub get
  # flutter pub run flutter_native_splash:create


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: quran
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
    - family: OttomanHafs
      fonts:
        - asset: assets/fonts/OttomanHafs/UthmanicHafs_V20.ttf